### ISSUE TITLE
Output contains part of the webpage, not just the terminal output...

### ISSUE THREAD

**Issue by r3v** [tav/asciinema2gif#16]
It works well, but I was expecting the output to resemble what is have embedded in README.md as an example.  Instead, the resulting gif contains a portion of the webpage. 

e.g: [http://i.imgur.com/g40TBU0.gifv](http://i.imgur.com/g40TBU0.gifv )

Is there an option I'm missing? If not, can this be added?

**Comment by vitorgalvao** [comment]
The issue is you’re giving the wrong URL. It needs to be of the form `https://asciinema.org/api/asciicasts/<number>`, while you’re likely giving `https://asciinema.org/a/<number>`. Alternatively, just give the number.
