### ISSUE TITLE
mktemp: too few X's in template ‘asciinema2gif’

### ISSUE THREAD

**Issue by richrd** [tav/asciinema2gif#18]
When running the example from the readme I get this:

```
$ ./asciinema2gif --theme solarized-light -o "${HOME}/Desktop/another.gif" https://asciinema.org/api/asciicasts/8332
mktemp: too few X's in template ‘asciinema2gif’
: No such file or directory
```

The same happens with any asciicast numer or url and with different settings.

**Comment by vitorgalvao** [comment]
The template [hasn’t used any `X`s for a two weeks](https://github.com/tav/asciinema2gif/commit/f994b73bd9c46b38d6433af58d22c7efb3c49d90).

Are you sure you’re not using an old version? And if you’re up to date, which OS are you on?

**Comment by richrd** [comment]
Yep, I just made sure I'm up to date. I noticed that this happens even when running `asciinema2gif` without any arguments. The line that triggers the error is here https://github.com/tav/asciinema2gif/commit/f994b73bd9c46b38d6433af58d22c7efb3c49d90#diff-ca3084f0c3636265c42f1d9db67c4a52R10 `readonly tempdir="$(mktemp -d -t asciinema2gif)"`

I'm on Kubuntu 15.04 with kernel 4.2.0-27-generic and a system upgrade didn't make a difference.

**Comment by vitorgalvao** [comment]
The reason I asked those specific questions is that I was the one to submit the changes, and it works on OS X (my setup). My first thought was that you were using some flavour of Linux, and that `mktemp` has different options. Seems like the case.

Please change that line to `readonly tempdir="$(mktemp -d -t asciinema2gif.XXXX)"`.

Does that fix it? Does it create the gif successfully?

**Comment by richrd** [comment]
Yep, #19 fixes it! Thanks very much, great job! :+1: 

The other error `: No such file or directory` was due to some problems with my `phantomjs` installation, but I got that fixed too.
