### ISSUE TITLE
Unclear Ubuntu installation docs

### ISSUE THREAD

**Issue by cezaraugusto** [tav/asciinema2gif#25]
Installing asciinema2gif from a MacOS was a breeze. However things are not quite clear with Ubuntu.

Any way to improve it?

**Comment by wong2** [comment]
@cezaraugusto what do you mean by unclear?

**Comment by sebmoule** [comment]
@wong2 I tried to install on ubuntu, but I get this error message : 
> asciinema2gif
> 
> This script has unmet dependencies. You need to install these first:
>   phantomjs

From where I have to install the Phantomjs2 ? It created the node_modules in the directory where is asciinema2gif, but it seams it don't find it

**Comment by vitorgalvao** [comment]
@sebmoule You probably installed it with `npm install phantomjs`. Was that the case? Install with `npm install -g phantomjs` so it becomes a global package (i.e. other apps can see it).

**Comment by sebmoule** [comment]
@vitorgalvao Thanks you very much that's exactly what I was looking for :)
