### ISSUE TITLE
Hanging on "preparing window..."

### ISSUE THREAD

**Issue by dawsonbotsford** [tav/asciinema2gif#26]
```sh
asciinema2gif https://asciinema.org/a/deo5wx7v8iok4dt4h7mrtei1e
>> Dimensions: 563x752
>> Preparing window ...
```

[sist](https://github.com/dawsonbotsford/sist) output:

### OS
Darwin  
x64  

### shell  
`uname`: Darwin
`echo $SHELL`: /bin/zsh
`echo $TERM`: xterm-256color
`echo $TERM_PROGRAM`: iTerm.app

### node  
`npm -v`: 2.14.2
`node --version`: v4.0.0

Time created: Wed Jul 27 2016 23:58:48 GMT-0700 (PDT)

**Comment by dawsonbotsford** [comment]
Bump

**Comment by wong2** [comment]
@dawsonbotsford https://asciinema.org/a/deo5wx7v8iok4dt4h7mrtei1e doesn't exist

**Comment by wong2** [comment]
and If you're using the latest version of asciinema2gif, it will raise an error of `wrong url format`

**Comment by dawsonbotsford** [comment]
Sorry I attached the wrong screenshot. Please re-open @wong2:

![](http://i.imgur.com/UZwIagP.png)

**Comment by vitorgalvao** [comment]
@dawsonbotsford Latest version is `0.4`.
