### ISSUE TITLE
"SSL handshake failed" while trying to convert an asciicast to a gif

### ISSUE THREAD

**Issue by alerac** [tav/asciinema2gif#30]
Hi,

Thanks a lot for your work which seems to work great. Nevertheless, I try to convert an asciicast to a gif following your examples and I face an SSL error. Actually, I run this command: 

`./asciinema2gif --theme solarized-light -o "${HOME}/Bureau/test.gif" https://asciinema.org/api/asciicasts/81648`

and I get the following error codes:

`ERROR: Couldn't open https://asciinema.org/api/asciicasts/81648?theme=solarized-light.`
`ERROR: SSL handshake failed`

My asciicast is public. And I get the same error codes while trying to run simply:

`./asciinema2gif --size small --speed 2 --theme solarized-light 81648`

Any idea why?

I just would like to note I think I have all the dependencies installed and I'm on Ubuntu 14.04 LTS

Many thanks for your help. Don't hesitate to tell me if I post in the wrong place...

**Comment by wong2** [comment]
can you try to replace this line: https://github.com/tav/asciinema2gif/blob/master/asciinema2gif#L113
to: `phantomjs --ssl-protocol=any "${rundir}/render.js" "${asciinema_url}"`

**Comment by alerac** [comment]
Hi,

Many thanks for your reply. This is perfect! It works now!!!

Cheers

**Comment by wong2** [comment]
great,  i'll make  a new release  with  it

Get Outlook for iOS




On Tue, Aug 9, 2016 at 7:29 PM +0800, "alerac" <notifications@github.com> wrote:












Closed #30.
