### ISSUE TITLE
'ReferenceError: Can't find variable: $'

### ISSUE THREAD

**Issue by dewyze** [tav/asciinema2gif#32]
I am following the exact command in the README and am getting the following result. I tried using both my own recordings and the default one on asciinema.org.

```
asciinema2gif --theme solarized-light -o "${HOME}/Desktop/another.gif" https://asciinema.org/api/asciicasts/8332
ReferenceError: Can't find variable: $

  undefined:2
  :4
```

The recording is of nothing. I simply started and then stopped the recorder and that was the error I received every time.

I am using OS X Sierra (or macOS or whatever it is called). I have used it in and out of tmux, and tried both bash and zsh. I have tried using node versions `0.10.30`, `4.6.0` and `6.4.0`. I am happy to try any other recommend debugging techniques if that would be helpful.

**Comment by dewyze** [comment]
I am thinking that jQuery is not being included inside the phantom js browser

**Comment by dewyze** [comment]
I confirmed that jQuery is not available inside of phantom js. At least on my setup, if you print out the dimensions [here](), they would be null.

I tried including `<page variable name>.injectJs("/Users/john/node_modules/jquery/dist/jquery.min.js");` right before lines [here](https://github.com/tav/asciinema2gif/blob/8ff73f41a030da074b33f4e58283b6bf8d6d6968/render.js#L57) and [here](https://github.com/tav/asciinema2gif/blob/8ff73f41a030da074b33f4e58283b6bf8d6d6968/render.js#L109) and that fixed it. I am not particularly familiar with node, so I am not sure what the best way to do that is. If you give me any guidance I am happy to open a PR.

**Comment by wong2** [comment]
@dewyze Thanks a lot. The issue is because asciinema.org removed jQuery from their page. 
So you are right, the solution is to inject jQuery to the page, I've made a PR: https://github.com/tav/asciinema2gif/pull/33

**Comment by dewyze** [comment]
I am going to close this for enough, because I assume that fixes my problem. Since it's not out in a release yet, I can't update via homebrew. But thanks for the quick turnaround!

**Comment by wong2** [comment]
@dewyze yeah, the release is waiting: https://github.com/Homebrew/homebrew-core/pull/5704
