### ISSUE TITLE
phantomjs binary name

### ISSUE THREAD

**Issue by zelahi** [tav/asciinema2gif#4]
I tried to use the script, and run it, however it could not find the binary: phantomjs2.
This is the error message I am recieving:

./asciinema2gif: line 19: phantomjs2: command not found

I checked in the binary for phantomjs2 and under phantomjs2/bin: I saw the name of the binary was phantomjs.  

I changed line 19 to phantomjs and ran the script and it worked afterwards.  Is this something that needs to be updated?

**Comment by tav** [comment]
Thanks @zelahi. The change is now in `master`, along with other changes to reflect changes on the asciinema site. It should all be working again now.

Cheers!
