### ISSUE TITLE
Gif generation memory leak

### ISSUE THREAD

**Issue by eonpatapon** [tav/asciinema2gif#42]
Once the gif generation starts it's eating all my available memory very quickly (like 8gb in a few seconds)

Using  master and:

gifsicle@3.0.4
imagemagick 6.9.5.10-1

**Comment by vitorgalvao** [comment]
Gif creation is completely offset to `imagemagick` and `gifsicle`, as you pointed out. Since the only think `asciinema2gif` is doing in that regard is calling those tools via bash, you need to make your case on those projects, not here.

**Comment by eonpatapon** [comment]
Indeed, sorry for the noise, apparently it's an issue imagemagick, not gifsicle
