### ISSUE TITLE
ReferenceError: Can't find variable: asciinema

### ISSUE THREAD

**Issue by ryrych** [tav/asciinema2gif#5]
asciinema2gif-0.1  ./asciinema2gif https://asciinema.org/a/18135

```bash
Creating and changing to temporary dir: /var/folders/6p/0dbj8n411c9379rh737dhk9m0000gn/T/asciinema2gif.XXX.CtygEhlR
>> Dimensions: 332x576
>> Preparing window ...
ReferenceError: Can't find variable: asciinema

  phantomjs://webpage.evaluate():9
  phantomjs://webpage.evaluate():42
```

I tried to use `phantomjs` but with no success.

**Comment by tomdee** [comment]
Yep, I've hit this too.

**Comment by ryrych** [comment]
This is due to new version and api of asciinema. As I can embed an image in Github that redirects to my public asciinema, I'm fine with that.
