### ISSUE TITLE
It's broken :-(

### ISSUE THREAD

**Issue by tknerr** [tav/asciinema2gif#6]
see #5

**Comment by yasoob** [comment]
Any update on this issue? :sob:

**Comment by wong2** [comment]
I've made it work again: https://github.com/tav/asciinema2gif/pull/7

**Comment by tav** [comment]
Hey guys, have merged in @wong2's and related fixes into `master`, so it should all be working again — at least, until asciinema change their website again :grinning:

Cheers!
